name: format

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  clang-tidy:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format
        run: |
          chmod +x utils/format-check.sh
          ./utils/format-check.sh
