name: lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    name: Run clang-tidy analysis
#    runs-on: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: src
          build-dir: build
          generator: Ninja
          c-compiler: gcc
          cxx-compiler: g++
          args:
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run clang-tidy
        run: |
          clang-tidy -p build src/*.cpp