name: lint

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  clang-tidy:
    name: Run clang-tidy analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: src
          build-dir: build
          generator: Ninja
          c-compiler: gcc
          cxx-compiler: g++
          args:
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run clang-tidy
        run: |
          chmod +x utils/lint-clang-tidy.sh
          ./utils/lint-clang-tidy.sh
  cppcheck:
    name: Run cppcheck analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cppcheck
        run: |
          sudo apt-get install -y cppcheck
      - name: Run clang-tidy
        run: |
          chmod +x utils/lint-cppckeck.sh
          ./utils/lint-cppcheck.sh
