name: build

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    name: Build the project
    #    runs-on: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Project
      uses: threeal/cmake-action@v1.3.0
      with:
        source-dir: src
        build-dir: build
        generator: Ninja
        c-compiler: gcc
        cxx-compiler: g++
    - name: Build project
      run: |
        cmake --build build
    - name: Cache build outputs
      id: cache-build-outputs
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ runner.os }}-build-outputs

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          ctest --test-dir build
