name: test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Build the project and run tests
    #    runs-on: [ubuntu-latest, windows-latest]
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Install utils
      run: |
        sudo apt-get install -y wget unzip

    - name: Install pre-built OpenCV
      run: |
        sudo apt-get install -y libopencv-dev=4.5.4+dfsg-9ubuntu4

    - name: Install pre-built Qt6
      run: |
        sudo apt-get install -y qt6-base-dev=6.2.4+dfsg-2ubuntu1.1 build-essential libgl1-mesa-dev libxkbcommon-x11-dev

      # no CUDA in GitHub Actions!
    # - name: Install CUDA
    #   uses: Jimver/cuda-toolkit@v0.2.15
    #   with:
    #     cuda: '12.4.1'

      # apt has outdated version (1.8.1)
    - name: Install LibTorch
      run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.2.2%2Bcpu.zip -O torch.zip
        unzip torch.zip
        cd libtorch
        echo "Torch_DIR=$(pwd)" >> $GITHUB_ENV
        cd ..

    - name: Install extra libraries
      run: |
        sudo apt install libfmt-dev

    - name: Configure Project
      uses: threeal/cmake-action@v1.3.0
      with:
        source-dir: src
        build-dir: build
        generator: Ninja
        c-compiler: gcc
        cxx-compiler: g++
        args:
          -DNO_USE_CUDA=ON
        build-args:
          -j10 -lfmt

    - name: Build project
      run: |
        cmake --build build

    - name: Run unit tests
      run: |
        ctest --test-dir build
