name: test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Build the project and run tests
    #    runs-on: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure Project
      uses: threeal/cmake-action@v1.3.0
      with:
        source-dir: src
        build-dir: build
        generator: Ninja
        c-compiler: gcc
        cxx-compiler: g++
        build-args:
          -j10
    - name: Build project
      run: |
        cmake --build build
    - name: Run unit tests
      run: |
        ctest --test-dir build
